class City {
  final String en;
  final String ar;

  City({required this.en, required this.ar});
}

class Governorate {
  final String en;
  final String ar;
  final List<City> cities;

  Governorate({required this.en, required this.ar, required this.cities});
}

final List<Governorate> egyptLocations = [
  Governorate(
    en: "Cairo",
    ar: "القاهرة",
    cities: [
      City(en: "Hadayek Al Zaiton", ar: "حدائق الزيتون"),
      City(en: "El Shorouk", ar: "الشروق"),
      City(en: "El Marg", ar: "المرج"),
      City(en: "Maadi Degla", ar: "المعادي دجلة"),
      City(en: "Abaseya", ar: "العباسية"),
      City(en: "New Nozha", ar: "النزهة الجديدة"),
      City(en: "Dar Al Salam", ar: "دار السلام"),
      City(en: "Al Kalaa", ar: "القلعة"),
      City(en: "Basateen", ar: "البساتين"),
      City(en: "Abdo Basha", ar: "عبده باشا"),
      City(en: "Nasr City", ar: "مدينة ناصر"),
      City(en: "15th Of May City", ar: "مدينة 15 مايو"),
      City(en: "5th Settlement", ar: "التجمع الخامس"),
      City(en: "Heliopolis", ar: "مصر الجديدة"),
      City(en: "3rd Settlement", ar: "التجمع الثالث"),
      City(en: "Ezbet El Nakhl", ar: "عزبة النخل"),
      City(en: "Katamiah", ar: "قطامية"),
      City(en: "El Herafieen", ar: "الحرفيين"),
      City(en: "Down Town", ar: "وسط البلد"),
      City(en: "New Maadi", ar: "المعادى الجديدة"),
      City(en: "Zamalek", ar: "الزمالك"),
      City(en: "1st Settlement", ar: "التجمع الاول"),
      City(en: "Helwan", ar: "حلوان"),
      City(en: "Al Zeitoun", ar: "الزيتون"),
      City(en: "Masaken Sheraton", ar: "مساكن شيراتون"),
      City(en: "Hadayek Helwan", ar: "حدائق حلوان"),
      City(en: "Ghamrah", ar: "غمره"),
      City(en: "Rod El Farag", ar: "روض الفرج"),
      City(en: "Al Matareya", ar: "المطرية"),
      City(en: "Al Kasr Al Einy", ar: "القصر العيني"),
      City(en: "New Cairo", ar: "القاهرة الجديدة"),
      City(en: "Ain Shams", ar: "عين شمس"),
      City(en: "Garden City", ar: "جاردن سيتي"),
      City(en: "Mirage City", ar: "ميراج سيتى"),
      City(en: "Amiria", ar: "العامرية"),
      City(en: "Al Azhar", ar: "الأزهر"),
      City(en: "Sayeda Zeinab", ar: "السيدة زينب"),
      City(en: "Almaza", ar: "الماظة"),
      City(en: "Fustat", ar: "الفسطاط"),
      City(en: "Hadayek Maadi", ar: "حدائق المعادي"),
      City(en: "Al Rehab", ar: "الرحاب"),
      City(en: "Al Moski", ar: "الموسكي"),
      City(en: "Manial Al Rodah", ar: "منيل الروضة"),
      City(en: "Maadi", ar: "المعادى"),
      City(en: "El Tahrir", ar: "التحرير"),
      City(en: "Gesr Al Suez", ar: "جسر السويس"),
      City(en: "Abdeen", ar: "عابدين"),
      City(en: "Mokattam", ar: "المقطم"),
      City(en: "Al Salam City", ar: "مدينة السلام"),
      City(en: "Misr El Kadima", ar: "مصر القديمة"),
      City(en: "Helmiet Elzaitoun", ar: "حلمية الزيتون"),
      City(en: "Al Daher", ar: "الضاهر"),
      City(en: "Hadayek Al Qobah", ar: "حدائق القبة"),
      City(en: "Shubra", ar: "شبرا"),
      City(en: "Cornish Al Nile", ar: "كورنيش النيل"),
      City(en: "Badr City", ar: "مدينة بدر"),
      City(en: "Ramsis", ar: "رمسيس"),
      City(en: "Madinty", ar: "مدينتي"),
      City(en: "Helmeya", ar: "الحلمية"),
    ],
  ),
  Governorate(
    en: "Giza",
    ar: "الجيزة",
    cities: [
      City(en: "6th of October", ar: "السادس من اكتوبر"),
      City(en: "Mansoureya", ar: "المنصورية"),
      City(en: "Hawamdya", ar: "الحوامدية"),
      City(en: "Tirsa", ar: "تيرسا"),
      City(en: "Abou Rawash", ar: "ابو رواش"),
      City(en: "Omraneya", ar: "العمرانية"),
      City(en: "Smart Village", ar: "القرية الذكية"),
      City(en: "Kerdasa", ar: "كرداسة"),
      City(en: "Saft El Laban", ar: "صفط اللبن"),
      City(en: "Dokki", ar: "الدقي"),
      City(en: "Al Saf", ar: "الصف"),
      City(en: "Sheikh Zayed", ar: "الشيخ زايد"),
      City(en: "Sakiat Mekki", ar: "ساقية مكي"),
      City(en: "Mohandessin", ar: "المهندسين"),
      City(en: "Al Kom Al Ahmer", ar: "الكوم الأحمر"),
      City(en: "Imbaba", ar: "إمبابة"),
      City(en: "Bolak Al Dakrour", ar: "بولاق الدكرور"),
      City(en: "Al Monib", ar: "المنيب"),
      City(en: "Berak Alkiaam", ar: "برك الكيام"),
      City(en: "Al Moatamadia", ar: "المعتمدية"),
      City(en: "Shabramant", ar: "شبرامانت"),
      City(en: "Warraq", ar: "الوراق"),
      City(en: "Manial", ar: "المنيل"),
      City(en: "Haram", ar: "الهرم"),
      City(en: "Agouza", ar: "العجوزة"),
      City(en: "Faisal", ar: "فيصل"),
      City(en: "Al Wahat", ar: "الواحات"),
      City(en: "Hadayeq El Ahram", ar: "حدائق الاهرام"),
      City(en: "Aossim", ar: "أوسيم"),
      City(en: "Al Nobariah", ar: "النوبارية"),
      City(en: "Badrashin", ar: "بدراشين"),
      City(en: "Kit Kat", ar: "كت كات"),
      City(en: "Al Barageel", ar: "البراجيل"),
      City(en: "Al Manashi", ar: "المناشي"),
    ],
  ),
  Governorate(
    en: "Alexandria",
    ar: "الإسكندرية",
    cities: [
      City(en: "Miami", ar: "ميامي"),
      City(en: "Smouha", ar: "سموحة"),
      City(en: "Abees", ar: "أبيس"),
      City(en: "Sedi Gaber", ar: "سيدي جابر"),
      City(en: "El Borg El Kadem", ar: "البرج القديم"),
      City(en: "Sedi Bisher", ar: "سيدي بشر"),
      City(en: "Al Bitash", ar: "البيطاش"),
      City(en: "Stanly", ar: "ستانلي"),
      City(en: "El-Agamy", ar: "العجمي"),
      City(en: "San Stefano", ar: "سان ستيفانو"),
      City(en: "Mahtet El-Raml", ar: "محطة الرمل"),
      City(en: "Al A'mriah", ar: "العامرية"),
      City(en: "Bangar EL Sokar", ar: "بنجر السكر"),
      City(en: "Manshia", ar: "المنشية"),
      City(en: "Sedi Kreir", ar: "سيدي كرير"),
      City(en: "Kafer Abdou", ar: "كفر عبده"),
      City(en: "Borg El Arab", ar: "برج العرب"),
      City(en: "Roshdy", ar: "رشدي"),
      City(en: "Abu Keer", ar: "ابو قير"),
      City(en: "Glem", ar: "جليم"),
      City(en: "Al Nahda Al Amria", ar: "النهضة العامرية"),
      City(en: "Awaied-Ras Souda", ar: "عويد راس سودا"),
      City(en: "Mandara", ar: "المندرة"),
      City(en: "City Center", ar: "وسط المدينة"),
      City(en: "Azarita", ar: "أزاريتا"),
      City(en: "Maamora", ar: "المعمورة"),
      City(en: "Al Soyof", ar: "السيوف"),
      City(en: "Sporting", ar: "سبورتنج"),
      City(en: "Khorshid", ar: "خورشيد"),
      City(en: "Luran", ar: "لوران"),
      City(en: "Asafra", ar: "العصافرة"),
      City(en: "Zezenya", ar: "زيزينيا"),
      City(en: "Muntazah", ar: "المنتزه"),
    ],
  ),
  Governorate(en: "Al Beheira", ar: "البحيرة", cities: [
    City(en: "Hosh Issa", ar: "حوش عيسى"),
    City(en: "Rashid", ar: "رشيد"),
    City(en: "Shubrakhit", ar: "شبراخيت"),
    City(en: "Edko", ar: "إدكو"),
    City(en: "Damanhour", ar: "دمنهور"),
    City(en: "Etay Al Barud", ar: "ايتاي البارود"),
    City(en: "Abu Hummus", ar: "ابو حمص"),
    City(en: "Kom Hamadah", ar: "كوم حمادة"),
    City(en: "Abou Al Matamer", ar: "ابو المطامير"),
    City(en: "Al Delengat", ar: "الدلنجات"),
    City(en: "El Nubariyah", ar: "النوبارية"),
    City(en: "Kafr El Dawwar", ar: "كفر الدوار"),
    City(en: "Edfina", ar: "إدفينا"),
    City(en: "Wadi Al Natroun", ar: "وادي النطرون"),
    City(en: "Al Mahmoudiyah", ar: "المحمودية"),
    City(en: "Al Rahmaniyah", ar: "الرحمانية"),
  ]),
  Governorate(en: "Al Daqahliya", ar: "الدقهلية", cities: [
    City(en: "Meet Ghamr", ar: "ميت غمر"),
    City(en: "Belqas", ar: "بلقاس"),
    City(en: "Nabroo", ar: "نابرو"),
    City(en: "Manzala", ar: "المنزلة"),
    City(en: "Shrbeen", ar: "شربين"),
    City(en: "El Sinblaween", ar: "السنبلاوين"),
    City(en: "Menit El Nasr", ar: "منية النصر"),
    City(en: "Dekernes", ar: "دكرنس"),
    City(en: "Aga", ar: "آجا"),
    City(en: "Talkha", ar: "طلخا"),
    City(en: "Al Mansoura", ar: "المنصورة"),
  ]),
  Governorate(en: "Al Fayoum", ar: "الفيوم", cities: [
    City(en: "Sonores", ar: "سنورس"),
    City(en: "Ebshoy", ar: "إبشواي"),
    City(en: "Kofooer Elniel", ar: "كفور النيل"),
    City(en: "New Fayoum", ar: "الفيوم الجديدة"),
    City(en: "Atsa", ar: "اطسا"),
    City(en: "Sanhoor", ar: "سنهور"),
    City(en: "Tameaa", ar: "طامية"),
    City(en: "Al Fayoum", ar: "الفيوم"),
    City(en: "Sersenaa", ar: "سيرسينا"),
    City(en: "El Aagamen", ar: "العجمين"),
    City(en: "Manshaa Abdalla", ar: "منشاء عبد الله"),
    City(en: "Youssef Sadek", ar: "يوسف صادق"),
    City(en: "Manshaa Elgamal", ar: "منشأة الجمال"),
  ]),
  Governorate(en: "Al Gharbia", ar: "الغربية", cities: [
    City(en: "Alsanta", ar: "السنطة"),
    City(en: "Al Mahala Al Kobra", ar: "المحلة الكبرى"),
    City(en: "Samanood", ar: "سمنود"),
    City(en: "Tanta", ar: "طنطا"),
    City(en: "Qotoor", ar: "قطور"),
    City(en: "Zefta", ar: "زفتى"),
    City(en: "Basyoon", ar: "بسيون"),
    City(en: "Kafr Alziat", ar: "كفر الزيات"),
  ]),
  Governorate(en: "Al Meniya", ar: "المنيا", cities: [
    City(en: "Minya", ar: "المنيا"),
    City(en: "Samaloot", ar: "سمالوط"),
    City(en: "Eladwa", ar: "العدوة"),
    City(en: "Mghagha", ar: "مغاغة"),
    City(en: "Matai", ar: "مطاى"),
    City(en: "Malawi", ar: "ملاوي"),
    City(en: "Bani Mazar", ar: "بني مزار"),
    City(en: "Dermwas", ar: "ديرماس"),
    City(en: "Abo Korkas", ar: "ابو قرقاص"),
  ]),
  Governorate(en: "Al Monufia", ar: "المنوفية", cities: [
    City(en: "Shohada", ar: "الشهداء"),
    City(en: "Menoof", ar: "منوف"),
    City(en: "Tala", ar: "تلا"),
    City(en: "Shebin El Koom", ar: "شبين الكوم"),
    City(en: "Sadat City", ar: "مدينة السادات"),
    City(en: "Quesna", ar: "قويسنا"),
    City(en: "Berket Al Sabei", ar: "بركة السبع"),
    City(en: "Ashmoon", ar: "أشمون"),
  ]),
  Governorate(en: "Al Sharqia", ar: "الشرقية", cities: [
    City(en: "Al Salhiya Al Gedida", ar: "الصالحية الجديدة"),
    City(en: "Abu Hammad", ar: "ابو حماد"),
    City(en: "Abu Kbeer", ar: "ابو كبير"),
    City(en: "Hehya", ar: "ههيا"),
    City(en: "Awlad Saqr", ar: "اولاد صقر"),
    City(en: "Al Hasiniya", ar: "الحسينية"),
    City(en: "Faqous", ar: "فاقوس"),
    City(en: "Darb Negm", ar: "درب نجم"),
    City(en: "Al Ibrahimiya", ar: "الابراهيمية"),
    City(en: "Zakazik", ar: "الزقازيق"),
    City(en: "Kafr Saqr", ar: "كفر صقر"),
    City(en: "Mashtool Al Sooq", ar: "مشتول السوق"),
    City(en: "Belbes", ar: "بيلبيس"),
    City(en: "Meniya Alqamh", ar: "منيا القمه"),
    City(en: "10th of Ramdan City", ar: "العاشر من رمضان"),
  ]),
  Governorate(en: "Aswan", ar: "أسوان", cities: [
    City(en: "Draw", ar: "دراو"),
    City(en: "El Klabsha", ar: "كلابشة"),
    City(en: "Al Sad Al Aali", ar: "السد العالي"),
    City(en: "Abu Simbel", ar: "أبو سمبل"),
    City(en: "Nasr Elnoba", ar: "نصر النوبة"),
    City(en: "Edfo", ar: "إدفو"),
    City(en: "Markaz Naser", ar: "مركز ناصر"),
    City(en: "Kom Ombo", ar: "كوم امبو"),
  ]),
  Governorate(en: "Asyut", ar: "أسيوط", cities: [
    City(en: "Dayrout", ar: "ديروط"),
    City(en: "Asyut", ar: "أسيوط"),
    City(en: "El Qusya", ar: "القوصية"),
    City(en: "Assuit Elgdeda", ar: "اسيوط الجديدة"),
    City(en: "Elfath", ar: "الفتح"),
    City(en: "El Ghnayem", ar: "الغنايم"),
    City(en: "Sahel Selim", ar: "ساحل سليم"),
    City(en: "Abnoub", ar: "أبنوب"),
    City(en: "El Badari", ar: "البدارى"),
    City(en: "Abou Teag", ar: "ابو تيج"),
    City(en: "Serfa", ar: "سيرفا"),
    City(en: "Manflout", ar: "منفلوط"),
  ]),
  Governorate(en: "Bani Souaif", ar: "بني سويف", cities: [
    City(en: "Bani Souaif", ar: "بني سويف"),
    City(en: "El Wastaa", ar: "الواسطى"),
    City(en: "El Korimat", ar: "الكريمات"),
    City(en: "El Fashn", ar: "الفشن"),
    City(en: "Naser", ar: "ناصر"),
    City(en: "Ahnaseaa", ar: "إهناسيا"),
    City(en: "New Bani Souaif", ar: "بني سويف الجديدة"),
    City(en: "Bebaa", ar: "ببا"),
    City(en: "Smostaa", ar: "سمسطا"),
  ]),
  Governorate(en: "Damietta", ar: "دمياط", cities: [
    City(en: "Kafr Saad", ar: "كفر سعد"),
    City(en: "Ras El Bar", ar: "رأس البر"),
    City(en: "Fareskor", ar: "فارسكور"),
    City(en: "Al Zarkah", ar: "الزرقا"),
    City(en: "Damietta", ar: "دمياط"),
    City(en: "New Damietta", ar: "دمياط الجديدة"),
  ]),
  Governorate(en: "Ismailia", ar: "الإسماعيلية", cities: [
    City(en: "Elsalhia Elgdida", ar: "الصالحية الجديدة"),
    City(en: "Al Kasaseen", ar: "القصاصين"),
    City(en: "Abo Sultan", ar: "ابو سلطان"),
    City(en: "El Tal El Kebir", ar: "التل الكبير"),
    City(en: "Abu Swer", ar: "ابو صوير"),
    City(en: "Qantera Gharb", ar: "قنطرة غرب"),
    City(en: "Qantera Sharq", ar: "القنطرة شرق"),
    City(en: "Nfeesha", ar: "نفيشة"),
    City(en: "Ismailia", ar: "الإسماعيلية"),
    City(en: "Srabioom", ar: "سرابيوم"),
    City(en: "Fayed", ar: "فايد"),
  ]),
  Governorate(en: "Kafr El Sheikh", ar: "كفر الشيخ", cities: [
    City(en: "Hamool", ar: "الحامول"),
    City(en: "Kafr El Sheikh", ar: "كفر الشيخ"),
    City(en: "Al Riadh", ar: "الرياض"),
    City(en: "Qeleen", ar: "قلين"),
    City(en: "Desouq", ar: "دسوق"),
    City(en: "Seedy Salem", ar: "سيدى سالم"),
    City(en: "Bela", ar: "بيلا"),
    City(en: "Fooh", ar: "فوه"),
    City(en: "Metobas", ar: "مطوبس"),
    City(en: "Borollos", ar: "برج البرلس"),
    City(en: "Balteem", ar: "بلطيم"),
  ]),
  Governorate(en: "Luxor", ar: "الأقصر", cities: [
    City(en: "El Karnak", ar: "الكرنك"),
    City(en: "El Korna", ar: "القرنة"),
    City(en: "Armant Sharq", ar: "ارمنت شرق"),
    City(en: "Esnaa", ar: "اسنا"),
    City(en: "Luxor", ar: "الأقصر"),
    City(en: "Armant Gharb", ar: "ارمنت غرب"),
  ]),
  Governorate(en: "Matrooh", ar: "مطروح", cities: [
    City(en: "Matrooh", ar: "مطروح"),
    City(en: "El Alamein", ar: "العلمين"),
    City(en: "Sidi Abdel Rahman", ar: "سيدي عبد الرحمن"),
    City(en: "El Dabaa", ar: "الضبعة"),
    City(en: "Marsa Matrooh", ar: "مرسى مطروح"),
  ]),
  Governorate(en: "New Valley", ar: "الوادي الجديد", cities: [
    City(en: "El Kharga", ar: "الخارجة"),
    City(en: "New Valley", ar: "الوادي الجديد"),
  ]),
  Governorate(en: "Port Said", ar: "بورسعيد", cities: [
    City(en: "Port Fouad", ar: "بور فؤاد"),
    City(en: "Port Said", ar: "بورسعيد"),
    City(en: "Zohoor District", ar: "حي الزهور"),
  ]),
  Governorate(en: "Qalyubia", ar: "القليوبية", cities: [
    City(en: "Abu Zaabal", ar: "ابو زعبل"),
    City(en: "Qaha", ar: "قها"),
    City(en: "Tookh", ar: "طوخ"),
    City(en: "El Oboor", ar: "العبور"),
    City(en: "Meet Nama", ar: "ميت نما"),
    City(en: "Al Shareaa Al Gadid", ar: "الشريعة الجديد"),
    City(en: "Banha", ar: "بنها"),
    City(en: "El Kanater EL Khayrya", ar: "القناطر الخيرية"),
    City(en: "Sheben Alkanater", ar: "شبين القناطر"),
    City(en: "El Qalag", ar: "القلج"),
    City(en: "Bahteem", ar: "بهتيم"),
    City(en: "Orabi", ar: "عرابي"),
    City(en: "Qalyoob", ar: "قليوب"),
    City(en: "Al Khanka", ar: "الخانكة"),
    City(en: "El Khsos", ar: "الخصوص"),
    City(en: "Kafr Shokr", ar: "كفر شكر"),
    City(en: "Om Bayoumi", ar: "أم بيومي"),
    City(en: "Shoubra Alkhema", ar: "شبرا الخيمة"),
    City(en: "Mostorod", ar: "مسطرد"),
  ]),
  Governorate(en: "Qena", ar: "قنا", cities: [
    City(en: "Deshna", ar: "دشنا"),
    City(en: "Abu Tesht", ar: "ابوتشت"),
    City(en: "Farshoot", ar: "فرشوط"),
    City(en: "Qena", ar: "قنا"),
    City(en: "Qoos", ar: "قوص"),
    City(en: "Naqada", ar: "نقادة"),
    City(en: "Naga Hamadi", ar: "نجع حمادي"),
  ]),
  Governorate(en: "Red Sea", ar: "البحر الاحمر", cities: [
    City(en: "Safaga", ar: "سفاجا"),
    City(en: "Hurghada", ar: "الغردقة"),
    City(en: "Qouseir", ar: "القصير"),
    City(en: "Marsa Alam", ar: "مرسى علم"),
    City(en: "Gouna", ar: "الجونة"),
    City(en: "Ras Ghareb", ar: "رأس غارب"),
  ]),
  Governorate(en: "Sohag", ar: "سوهاج", cities: [
    City(en: "Tema", ar: "طما"),
    City(en: "Saqatlah", ar: "ساقلته"),
    City(en: "Dar Elsalam", ar: "دار السلام"),
    City(en: "Gerga", ar: "جرجا"),
    City(en: "Elbalyna", ar: "البالينا"),
    City(en: "Maragha", ar: "مراغة"),
    City(en: "El Monshah", ar: "المنشاه"),
    City(en: "Ghena", ar: "جهينة"),
    City(en: "Akhmem", ar: "أخميم"),
    City(en: "Tahta", ar: "طهطا"),
  ]),
  Governorate(en: "Suez", ar: "السويس", cities: [
    City(en: "Ataka District", ar: "حي عتاقة"),
    City(en: "Suez", ar: "السويس"),
    City(en: "Elganaien District", ar: "حي الجناين"),
    City(en: "Al Suez", ar: "السويس"),
    City(en: "Al Adabya", ar: "الأدبية"),
    City(en: "Ain Al Sukhna", ar: "العين السخنة"),
    City(en: "El Arbeen District", ar: "حى الاربعين"),
  ]),
  Governorate(en: "North Sinai", ar: "شمال سيناء", cities: [
    City(en: "Al Arish", ar: "العريش"),
  ]),
  Governorate(en: "South Sinai", ar: "جنوب سيناء", cities: [
    City(en: "Neweibaa", ar: "نويبع"),
    City(en: "Dahab", ar: "دهب"),
    City(en: "Saint Catherine", ar: "سانت كاترين"),
    City(en: "Sharm Al Sheikh", ar: "شرم الشيخ"),
    City(en: "Toor Sinai", ar: "طور سيناء"),
    City(en: "Taba", ar: "طابا"),
  ]),
];
