"use client";

import { useState } from "react";
import { DateRangeType } from "@/app/admin/dashboard-actions";
import { StatsGrid } from "./_components/dashboard/StatsGrid";
import { ChartsSection } from "./_components/dashboard/ChartsSection";
import { ActivityFeed } from "./_components/dashboard/ActivityFeed";
import { TopProducts } from "./_components/dashboard/TopProducts";
import { useRouter } from "next/navigation";
import Link from "next/link";

import { DashboardStats } from "./dashboard-actions";

interface DashboardClientProps {
    initialStats: DashboardStats;
    searchParams: { range?: string };
}

export default function DashboardClient({ initialStats, searchParams }: DashboardClientProps) {
    const router = useRouter();
    const [range, setRange] = useState<DateRangeType>((searchParams.range as DateRangeType) || '30d');
    const stats = initialStats; // Use props directly as page refreshes on navigation
    
    // In a real implementation with client-side only transitions we'd fetch here.
    // However, to keep it simple and SEO/Server Action friendly, we'll just navigate.
    // The parent page will re-fetch based on URL params.
    const handleRangeChange = (newRange: DateRangeType) => {
        setRange(newRange);
        router.push(`/admin?range=${newRange}`);
    };

    return (
        <div>
            {/* Header */}
            <div className="admin-header">
                <div>
                    <h1 className="admin-title">Dashboard</h1>
                    <p className="admin-subtitle">Welcome to your command center.</p>
                </div>
                <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                    <div className="admin-tabs-container" style={{ background: 'white', border: '1px solid var(--admin-border)', padding: '4px', borderRadius: '8px' }}>
                        {(['7d', '30d', '90d', '12m'] as const).map((r) => (
                            <button
                                key={r}
                                onClick={() => handleRangeChange(r)}
                                className={`admin-btn ${range === r ? 'admin-btn-primary' : 'admin-btn-ghost'}`}
                                style={{ padding: '6px 12px', fontSize: '12px' }}
                            >
                                {r.toUpperCase()}
                            </button>
                        ))}
                    </div>
                </div>
            </div>

            {/* Smart Insights (Static for now, could be dynamic) */}
            <div style={{ 
                background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)', 
                borderRadius: '12px', 
                padding: '20px', 
                color: 'white',
                marginBottom: '32px',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                boxShadow: '0 10px 25px -5px rgba(79, 70, 229, 0.4)'
            }}>
                <div>
                    <h3 style={{ margin: 0, fontSize: '18px', fontWeight: 600 }}>🚀 Business Update</h3>
                    <p style={{ margin: '8px 0 0 0', opacity: 0.9, fontSize: '14px' }}>
                        Revenue is up <strong style={{ color: '#a5f3fc' }}>{stats.kpi.revenue.change.toFixed(1)}%</strong> compared to the previous period. Great job!
                    </p>
                </div>
                <Link href="/admin/marketing" className="admin-btn" style={{ background: 'rgba(255,255,255,0.2)', border: 'none', color: 'white', backdropFilter: 'blur(10px)' }}>
                    View Campaigns
                </Link>
            </div>

            <StatsGrid stats={stats} />

            <ChartsSection charts={stats.charts} />

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '24px', marginTop: '24px' }}>
                <TopProducts products={stats.lists.topProducts} />
                <ActivityFeed initialActivity={stats.lists.recentActivity} />
            </div>
            
            <div style={{ marginTop: '40px', textAlign: 'center', fontSize: '12px', color: 'var(--admin-text-muted)' }}>
                Generated by The Greatest Dashboard Engine • Last updated {new Date().toLocaleTimeString()}
            </div>
        </div>
    );
}
